name = "Selasia"
author = "Wafflasy/Xaminia/Whispree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c9fe5cd03310846816c179dc310ef4203f61b6185e023d0a36db4d7cd3b6a4f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
